name: CI
on:
    push:
        branches:
          - "**"
jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v3
              with:
                  node-version: 18
            - run: npm ci
            - name: Install Changeset
              run: npm install -g @changesets/cli
            - name: fix tsup
              run: npm i -D tsup typescript
            - name: Prepare for Publish
              run: "npm run lint && npm test"
            - name: Build
              run: npm run build --if-present
     
    publish:
        name: Publish
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v3
              with:
                  node-version: 18
            - run: npm ci
            - name: Install Changeset
              run: npm install -g @changesets/cli
            - name: fix tsup
              run: npm i -D tsup typescript
            - name: Prepare for Publish
              run: "npm run lint && npm test"
            - name: Build
              run: npm run build --if-present
            - name: Publish
              run: npx changeset publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}