name: CI
on:
    push:
        branches:
          - "**"
jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v3
              with:
                  node-version: 18
            - run: npm ci
            - name: Install Changeset
              run: npm install -g @changesets/cli
            - name: fix tsup
              run: npm i -D tsup typescript
            - name: Prepare for Publish
              run: "npm run lint && npm test"
            - name: Build
              run: npm run build --if-present
     
    publish:
        name: Publish
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v3
              with:
                  node-version: 18
            - run: npm ci
            - name: Install Changeset
              run: npm install -g @changesets/cli
            - name: fix tsup
              run: npm i -D tsup typescript
            - name: Prepare for Publish
              run: "npm run lint && npm test"
            - name: Build
              run: npm run build --if-present
            - name: Versionning
              run: npx changeset version
            - id: publish
              uses: JS-DevTools/npm-publish@v2.2.2
              with:
                token: ${{ secrets.NPM_TOKEN }}
                access: public
            - if: ${{ steps.publish.outputs.type }}
              run: echo "Version changed!"
            - name: Save version
              run: |
                git config user.name github-actions
                git config user.email github-actions@github.com
                git add .
                git commit -m "generated"
                git push